### ISSUE TITLE
Can't use captured groups in auto text

### ISSUE THREAD

**Issue by perilstar** [5zig/The-5zig-Mod-Docs#2]
What I did:
Create an Auto Text chat filter entry with Regex, Chat message: ".*test(\d{3})", Auto Text: "$1"

What I expected to happen:
When I type "test123" in chat, I should automatically say "123"

What happened:
When I type "test123" in chat, I automatically say "$1"

Please Add/Fix/Document this feature so I can use it :smile:

**Comment by 5zig** [comment]
Hi, the chat filter in the mod is a little different to the way it works in regex. You need to use ${1} instead of just $1 if you want to use the matched group. There are also some other features of the chat filter, like random selection and more, but unfortunately I didn't have time yet to create a documentation for it.
Some features can be found [here](http://5zig.net/log) for Version 3.9.15. There is also an explanation video from another mod user, which you can find [here](https://youtu.be/g5OOfjKMTIA).
